image: Visual Studio 2017

environment:
    PYTHON_HOME: 'C:/Python27'

branches:
  only:
    - ghini-1.0-mrbg

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%;C:\Program Files (x86)\NSIS\Bin
  - ps: if (-not (Test-Path pygtk-all-in-one-2.24.2.win32-py2.7.msi)) { Start-FileDownload "https://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi" }
  - ps: Get-FileHash pygtk-all-in-one-2.24.2.win32-py2.7.msi -Algorithm MD5 # 4bddf847f81d8de2d73048b113da3dd5
  - 'msiexec /i pygtk-all-in-one-2.24.2.win32-py2.7.msi /qn /norestart /log pygtk-install.log TARGETDIR=C:\Python27 ALLUSERS=1'
  - 'pip install py2exe_py2'
  - 'pip install psycopg2'
  - 'pip install pygments'

build_script:
  - 'mkdir dist'
  - 'pip install .'
  - 'python setup.py py2exe'
  - 'python setup.py nsis'

cache:
  - pygtk-all-in-one-2.24.2.win32-py2.7.msi

artifacts:
  - path: dist/ghini.desktop-*-setup.exe

test: off

deploy:
  release: 'v1.0.86 (MRBG Branch)' # :bump
  description: ''
  provider: GitHub
  auth_token:
    secure: m0gg+fMh1ot3TOipC0zQmOQNABEZUE5Xbkg6nR9Hl3kK05u/u0qcWkdJFIOHGeh3
  draft: false
  prerelease: false
  # on:
  #   appveyor_repo_tag: true        # deploy on tag push only
