language: python

python: 
    - "3.4"

virtualenv:
    system_site_packages: true

before_install: 
    # Environment setup
    - sudo apt-get -qq update
    - sudo apt-get install gettext python3-gi python-lxml git libxslt1-dev pkg-config libjpeg-dev build-essential python-all-dev
    - sudo apt-get install gir1.2-gtk-3.0
    - sudo apt-get install python-nose
    - sudo apt-get install -y gir1.2-champlain-0.12 gir1.2-gtkchamplain-0.12 gir1.2-gtkclutter-1.0
    - pip install pip --upgrade
    - pip install --upgrade gevent
    - export VIRT_ROOT=/home/travis/virtualenv/python$TRAVIS_PYTHON_VERSION
    - mkdir -p $VIRT_ROOT/share
    # build before install
    - python setup.py -q build

install:
    - pip install coveralls
    - pip install .

script:
    - coverage run --source=bauble setup.py test

after_success:
    - coveralls
