[pytest]
markers =
    no_setup_test_data: Skip database setup for tests that don't require it.
    postgresql: Tests that require a PostgreSQL database or postgres-check lane.
cache_dir = /tmp/pytest_cache
testpaths = bauble/test bauble/plugins
python_files = test*.py