#!/bin/sh
set -e

# Automatically added by dhpython:
if which pycompile >/dev/null 2>&1; then
	pycompile -p bauble /usr/lib/python2.7/dist-packages/bauble -V 2.7-
fi

# End automatically added section
# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section
