#!/bin/sh

TAG_NAME="$1"
if [ "$TAG_NAME" == "" ] ; then
	echo "ERROR: enter a tag name"
	exit 1
fi

REPO_ROOT="svn+ssh://batoms@forgesvn1.novell.com/svn/bauble"
#REPO_ROOT="https://batoms@forgesvn1.novell.com/svn/bauble"
svn copy -m "" -rHEAD $REPO_ROOT/trunk $REPO_ROOT/tags/$TAG_NAME