.TH ghini 1 "MAY 2018" Linux "User Manuals"
.SH NAME
ghini \- software application to manage a collection of botanical specimens
.SH SYNOPSIS
.B ghini
.SH DESCRIPTION
.B Ghini
is a software suite of programs for the management of botanical collections.  The graphical (X) application
.B ghini
is part of it, and is generally referred to as
.B ghini.desktop
.
.BR
.B ghini.desktop
was born as
.B Bauble
at the Belize Botanical Gardens, and is supported by several other gardens, which have adopted it.
.BR
Other members of the suite, not described here, are
.B ghini.pocket
(an Android app),
.B ghini.web
(a nodejs server), and
.B ghini.tour
(an Android app).  
.BR
The documentation is available through the help menu in ghini application.
.BR
The programs are documented fully in the runtime documentation.
.SH AUTHOR
Ghini is maintained by Mario Frasca.
.BR
Bauble was written by Brett Adams.
.PP
This manual page was written by Mario Frasca <mario@anche.no>,
for the Debian project (and may be used by others).
