#!/bin/sh

TAG_NAME="$1"

if [ "$TAG_NAME" = "" ] ; then
	echo "ERROR: enter a tag name"
	exit 1
fi
REPO_ROOT="https://forgesvn1.novell.com/svn/bauble"
svn copy -rHEAD "$REPO_ROOT/trunk" "$REPO_ROOT/tags/$TAG_NAME"