#!/bin/bash

ECHO=

if [ "$1" == "" ]
then
  branch=ghini-3.1-dev
elif expr "$1" : '[0-9]\+$' >/dev/null
then
  branch=ghini-issue-$1
elif expr "$1" : '[0-9]\.[0-9]\+$' >/dev/null
then
  branch=ghini-$1-dev
else
  branch=ghini-$1
fi

venv=$(echo $branch | sed -e 's/ghini/ghide/' -e 's/→/-/')

$ECHO git checkout $branch
$ECHO . ~/.virtualenvs/$venv/bin/activate
