name: ghini
version: '1.0.90'
summary: ghini, a botanic collections manager
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

base: core18
grade: devel
confinement: devmode

apps:
  ghini10:
    command: desktop-launch $SNAP/bin/ghini
    plugs: [unity7, x11, opengl, gsettings, home, removable-media, raw-usb]
    desktop: share/applications/ghini.desktop

parts:
  ghini:
    plugin: python
    python-version: python2
    python-packages:
           - python-gtk2
           - python-pil
           - python-setuptools
           - ghini

    install: |
      pip install ghini.desktop